""" Create a Turtle, name it, make it BLUE and draw a Smiley Face"""
import turtle
ben = turtle.Turtle()
ben.color('Blue')
ben.speed(0)
ben.up()
ben.goto(0, -300)
ben.down()
ben.circle(300)
ben.up()
ben.goto(100,100)
ben.down()
ben.circle(50)
ben.up()
ben.goto(-100,100)
ben.down()
ben.circle(50)
ben.up()
ben.goto(40,-80)
ben.down()
ben.right(90)
for x in range(180):
    ben.forward(1)
    ben.right(1)
ben.right(90)
ben.forward(118)
input()
from Myfile.py import polygon
polygon(12)
input()
